# Generated by Django 3.0.8 on 2020-08-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='CollegeClass',
        ),
    ]
