# Generated by Django 3.0.8 on 2020-08-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_auto_20200802_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='college_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.CollegeClass'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.College')),
            ],
        ),
        migrations.AlterField(
            model_name='collegeclass',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearn.Department'),
        ),
    ]
