# Generated by Django 3.1 on 2020-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_sybadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
