# Generated by Django 3.1 on 2021-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_auto_20201228_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='classworkpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
