# Generated by Django 3.0.8 on 2020-08-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('elearn', '0003_auto_20200802_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='college_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='college_class',
            field=models.ManyToManyField(blank=True, null=True, to='elearn.CollegeClass'),
        ),
    ]
