# Generated by Django 3.1 on 2021-01-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_classworkpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=256, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.student')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('postcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.postcomment')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTestSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('classtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classtestpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.student')),
            ],
        ),
    ]
