# Generated by Django 3.0.8 on 2020-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_auto_20200804_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college_class',
            field=models.ManyToManyField(blank=True, to='elearn.CollegeClass'),
        ),
    ]
