# Generated by Django 3.1 on 2020-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_subject_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='college_class',
        ),
        migrations.AddField(
            model_name='collegeclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='elearn.Subject'),
        ),
    ]
