# Generated by Django 3.1 on 2021-01-05 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_classtestsolution_commentreply_studentchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classworkpost',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
