# Generated by Django 3.1 on 2021-01-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_auto_20210106_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classworkpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
