# Generated by Django 3.1 on 2020-09-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_auto_20200907_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.college'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
