# Generated by Django 3.0.8 on 2020-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_auto_20200810_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeclass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
