# Generated by Django 3.1 on 2021-01-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0006_auto_20210106_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchoice',
            name='choice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.choice'),
        ),
    ]
