# Generated by Django 3.1 on 2020-08-20 18:38

import django.db.models.deletion
from django.db import migrations, models

import elearn.models


class Migration(migrations.Migration):
    dependencies = [
        ('elearn', '0007_auto_20200812_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=256, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('college_class',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.collegeclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassWorkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_assignment', models.BooleanField(default=False)),
                ('college_class',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.collegeclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.FileField(upload_to=elearn.models.user_document_directory_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.ImageField(upload_to=elearn.models.user_image_directory_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.CreateModel(
            name='LinkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('class_test_post',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classtestpost')),
            ],
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.FileField(upload_to=elearn.models.user_video_directory_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.CharField(blank=True, max_length=256, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.classworkpost')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassWork',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.question'),
        ),
    ]
