# Generated by Django 3.1 on 2021-01-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0007_auto_20210108_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.choice'),
        ),
    ]
