# Generated by Django 3.1 on 2021-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0008_auto_20210108_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtestsolution',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
