# Generated by Django 3.1 on 2020-08-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('elearn', '0009_auto_20200821_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='classworkpost',
            name='student',
            field=models.ManyToManyField(blank=True, to='elearn.Student'),
        ),
    ]
