# Generated by Django 3.1 on 2020-08-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0010_classworkpost_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtestpost',
            old_name='student',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='classworkpost',
            old_name='student',
            new_name='students',
        ),
    ]
