# Generated by Django 3.1 on 2021-01-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0017_commentreply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
