# Generated by Django 3.1 on 2021-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0018_auto_20210122_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='used_storage_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='allotted_storage_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
