# Generated by Django 3.1.6 on 2021-02-04 17:27

from django.db import migrations, models

import elearn.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0019_auto_20210204_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsolution',
            name='file_url',
            field=models.FileField(upload_to=elearn.models.file_directory_path, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpost',
            name='document_url',
            field=models.FileField(upload_to=elearn.models.document_directory_path, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image_url',
            field=models.ImageField(upload_to=elearn.models.image_directory_path, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_url',
            field=models.FileField(upload_to=elearn.models.video_directory_path, blank=True, null=True),
        ),
    ]
