# Generated by Django 3.1.6 on 2021-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0020_auto_20210204_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='marked_as_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='marked_as_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
