# Generated by Django 3.1.6 on 2021-02-05 15:43
from django.contrib.auth.models import Group
from django.db import migrations


def forwards_func(apps, schema_editor):
    Group.objects.get_or_create(name='sybadmin')
    Group.objects.get_or_create(name='collegeadmin')
    Group.objects.get_or_create(name='teacher')
    Group.objects.get_or_create(name='student')


def reverse_func(apps, schema_editor):
    group1 = Group.objects.get(name='sybadmin')
    group2 = Group.objects.get(name='collegeadmin')
    group3 = Group.objects.get(name='teacher')
    group4 = Group.objects.get(name='student')

    group1.delete()
    group2.delete()
    group3.delete()
    group4.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('elearn', '0020_auto_20210204_2257'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
