# Generated by Django 3.1.6 on 2021-02-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0022_auto_20210205_2113'),
        ('elearn', '0021_auto_20210205_1644'),
    ]

    operations = [
    ]
