# Generated by Django 3.1.6 on 2021-02-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0023_merge_20210205_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
