# Generated by Django 3.1.6 on 2021-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0025_auto_20210209_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
    ]
