# Generated by Django 3.1.6 on 2021-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0026_college_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='plan_cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
